[ 2024-01-04 16:16:54,381,381 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:16:54,749,749 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:16:54,749,749 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:16:54,749,749 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:16:54,750,750 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:16:54,750,750 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36765720000039437
[ 2024-01-04 16:16:54,751,751 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:16:54,753,753 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:16:55,100,100 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:16:55,101,101 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:16:55,101,101 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:16:55,101,101 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:16:55,101,101 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34667350000017905
[ 2024-01-04 16:16:55,102,102 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:16:55,105,105 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:16:55,795,795 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:16:55,796,796 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:16:55,796,796 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:16:55,796,796 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:16:55,796,796 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:16:55,796,796 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5832', 'verifyId': 'e2b487928ea24bac87a4a9e47e94f499'}
[ 2024-01-04 16:16:55,797,797 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:16:55,797,797 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:16:55,797,797 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3474603999966348
[ 2024-01-04 16:16:55,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:16:55,800,800 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:16:56,525,525 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '2846', 'verifyId': '6aa66ec907bb419689cff5066159dc19'}
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:16:56,526,526 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.38648079999984475
[ 2024-01-04 16:16:56,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:16:56,530,530 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:16:57,267,267 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:16:57,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:16:57,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:16:57,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:16:57,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:16:57,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '6857', 'verifyId': 'bab3e319d61c4a818dcbd11008df4933'}
[ 2024-01-04 16:16:57,269,269 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:16:57,269,269 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:16:57,269,269 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4065614999999525
[ 2024-01-04 16:16:57,270,270 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:17:52,960,960 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:17:53,332,332 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:17:53,333,333 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:17:53,334,334 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:17:53,334,334 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:17:53,334,334 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37035069999910775
[ 2024-01-04 16:17:53,336,336 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:17:53,340,340 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:17:53,709,709 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:17:53,710,710 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:17:53,710,710 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:17:53,710,710 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:17:53,710,710 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36905509999996866
[ 2024-01-04 16:17:53,711,711 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:17:53,715,715 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:17:54,408,408 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:17:54,408,408 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:17:54,408,408 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5481', 'verifyId': '2656e1b8ead54e2b87ccc29af8f9c6f7'}
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:17:54,409,409 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3648899000036181
[ 2024-01-04 16:17:54,410,410 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:17:54,413,413 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:17:55,113,113 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:17:55,113,113 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:17:55,113,113 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:17:55,113,113 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:17:55,114,114 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:17:55,114,114 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '6706', 'verifyId': '04bce00e1f154a309f31c588c622af56'}
[ 2024-01-04 16:17:55,114,114 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:17:55,114,114 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:17:55,114,114 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3380165999988094
[ 2024-01-04 16:17:55,115,115 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:17:55,118,118 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:17:55,822,822 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:17:55,824,824 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:17:55,824,824 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:17:55,824,824 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:17:55,825,825 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:17:55,825,825 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '9079', 'verifyId': '76bf44bc8cd04d32b7231551efa14472'}
[ 2024-01-04 16:17:55,825,825 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:17:55,825,825 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:17:55,826,826 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3843044999994163
[ 2024-01-04 16:17:55,827,827 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:19:51,425,425 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:19:51,761,761 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:19:51,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:19:51,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:19:51,762,762 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:19:51,762,762 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33605249999891385
[ 2024-01-04 16:19:51,763,763 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:19:51,765,765 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:19:52,120,120 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:19:52,120,120 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:19:52,120,120 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:19:52,121,121 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:19:52,121,121 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3539468000017223
[ 2024-01-04 16:19:52,122,122 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:19:52,125,125 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:19:52,862,862 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:19:52,862,862 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:19:52,862,862 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:19:52,862,862 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:19:52,862,862 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:19:52,863,863 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '2091', 'verifyId': '36f7ccd9645c43e787bca4c7dd1da6dd'}
[ 2024-01-04 16:19:52,863,863 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:19:52,863,863 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:19:52,863,863 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3531022999995912
[ 2024-01-04 16:19:52,864,864 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:19:52,866,866 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:19:53,581,581 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:19:53,581,581 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:19:53,581,581 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '7657', 'verifyId': '4e39e5a497b940fa926ef0b234808e1d'}
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:19:53,582,582 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3514997999991465
[ 2024-01-04 16:19:53,583,583 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:19:53,585,585 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:19:54,299,299 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:19:54,300,300 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:19:54,300,300 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:19:54,300,300 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:19:54,300,300 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:19:54,301,301 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '8103', 'verifyId': '2dc82d5399a546cea5b9480a4b7a4309'}
[ 2024-01-04 16:19:54,301,301 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:19:54,301,301 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:19:54,301,301 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37631770000007236
[ 2024-01-04 16:19:54,302,302 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:22:16,504,504 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:22:16,877,877 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:22:16,877,877 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:22:16,877,877 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:22:16,878,878 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:22:16,878,878 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3709013000006962
[ 2024-01-04 16:22:16,879,879 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:22:16,882,882 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:22:17,284,284 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:22:17,285,285 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:22:17,285,285 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:22:17,285,285 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:22:17,285,285 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.40265639999779523
[ 2024-01-04 16:22:17,287,287 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:22:17,290,290 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:22:17,995,995 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '1148', 'verifyId': 'c64546d11847441ebad5dc2196185dca'}
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:22:17,996,996 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3716564999995171
[ 2024-01-04 16:22:17,997,997 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:22:18,000,000 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:22:18,692,692 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:22:18,692,692 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:22:18,692,692 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:22:18,692,692 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:22:18,692,692 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:22:18,693,693 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '8185', 'verifyId': '62405aaf52294bfba853e56d7c53bfe4'}
[ 2024-01-04 16:22:18,693,693 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:22:18,693,693 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:22:18,693,693 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3616524999997637
[ 2024-01-04 16:22:18,694,694 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:22:18,701,701 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:22:19,449,449 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:22:19,451,451 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:22:19,451,451 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:22:19,451,451 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:22:19,453,453 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:22:19,453,453 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '6798', 'verifyId': '8c714989ed834beab48843a05363cc18'}
[ 2024-01-04 16:22:19,454,454 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:22:19,454,454 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:22:19,455,455 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36896770000021206
[ 2024-01-04 16:22:19,458,458 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:29:24,699,699 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:29:25,071,071 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:29:25,071,071 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:29:25,072,072 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:29:25,072,072 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:29:25,072,072 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37074890000076266
[ 2024-01-04 16:29:25,073,073 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:29:25,076,076 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:29:25,418,418 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:29:25,419,419 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:29:25,419,419 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:29:25,419,419 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:29:25,419,419 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3420468999975128
[ 2024-01-04 16:29:25,420,420 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:29:25,424,424 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:29:26,193,193 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:29:26,194,194 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:29:26,195,195 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:29:26,195,195 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:29:26,196,196 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:29:26,196,196 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7589', 'verifyId': '7ca8a1ba4717472bb9bb2ec4b670aebd'}
[ 2024-01-04 16:29:26,197,197 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:29:26,197,197 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:29:26,198,198 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4104213999999047
[ 2024-01-04 16:29:26,201,201 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:29:26,206,206 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:29:26,918,918 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:29:26,919,919 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:29:26,919,919 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:29:26,919,919 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:29:26,920,920 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:29:26,920,920 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '3685', 'verifyId': 'd654193434b0405ba6195a7bb4d490e3'}
[ 2024-01-04 16:29:26,920,920 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:29:26,920,920 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:29:26,921,921 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3590193999989424
[ 2024-01-04 16:29:26,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:29:26,927,927 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:29:27,759,759 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:29:27,760,760 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:29:27,760,760 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:29:27,760,760 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:29:27,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:29:27,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '3920', 'verifyId': 'a76c10a8c52545f9a2865b4577a5fff8'}
[ 2024-01-04 16:29:27,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:29:27,761,761 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:29:27,762,762 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4697870000018156
[ 2024-01-04 16:29:27,764,764 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:36:31,467,467 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.44826880000255187
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:36:31,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:36:32,273,273 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:36:32,273,273 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:36:32,274,274 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:36:32,274,274 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:36:32,274,274 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3422437000008358
[ 2024-01-04 16:36:32,275,275 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:36:32,278,278 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:36:32,945,945 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:36:32,946,946 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:36:32,946,946 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:36:32,946,946 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:36:32,946,946 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:36:32,946,946 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '3532', 'verifyId': '3526c26a5ce54558866b02a41e09fe1c'}
[ 2024-01-04 16:36:32,947,947 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:36:32,947,947 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:36:32,947,947 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34155570000075386
[ 2024-01-04 16:36:32,948,948 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:36:32,950,950 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:36:33,615,615 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:36:33,615,615 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:36:33,615,615 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:36:33,615,615 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:36:33,616,616 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:36:33,616,616 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '1474', 'verifyId': 'ec7d139a3c024459b65bbaa2024acfca'}
[ 2024-01-04 16:36:33,616,616 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:36:33,616,616 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:36:33,616,616 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34011629999804427
[ 2024-01-04 16:36:33,617,617 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:36:33,620,620 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:36:34,341,341 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:36:34,342,342 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:36:34,342,342 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:36:34,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:36:34,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:36:34,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '1106', 'verifyId': '22040eff6cf94133923ac1733468c92f'}
[ 2024-01-04 16:36:34,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:36:34,344,344 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:36:34,344,344 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3965731999996933
[ 2024-01-04 16:36:34,346,346 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:41:55,156,156 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:41:55,505,505 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:41:55,506,506 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:41:55,506,506 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:41:55,506,506 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:41:55,506,506 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3482895999986795
[ 2024-01-04 16:41:55,507,507 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:41:55,510,510 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:41:55,868,868 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:41:55,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:41:55,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:41:55,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:41:55,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.35768610000013723
[ 2024-01-04 16:41:55,870,870 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:41:55,873,873 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:41:56,545,545 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:41:56,546,546 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:41:56,546,546 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:41:56,546,546 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:41:56,546,546 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:41:56,547,547 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5151', 'verifyId': '14e0c336b06e40ac97edfb47de2e6ddf'}
[ 2024-01-04 16:41:56,547,547 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:41:56,547,547 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:41:56,547,547 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3523115999996662
[ 2024-01-04 16:41:56,550,550 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:41:56,554,554 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:41:57,231,231 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:41:57,231,231 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:41:57,231,231 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:41:57,231,231 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:41:57,232,232 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:41:57,232,232 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '9369', 'verifyId': 'd66162688f444ab2ab73cf4a3dfb1c5c'}
[ 2024-01-04 16:41:57,232,232 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:41:57,232,232 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:41:57,232,232 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34288110000125016
[ 2024-01-04 16:41:57,233,233 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:41:57,235,235 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:41:57,983,983 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:41:57,984,984 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:41:57,985,985 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:41:57,985,985 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:41:57,985,985 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:41:57,985,985 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7868', 'verifyId': '9f47c7da30d5461e8f7f68e9304f7df4'}
[ 2024-01-04 16:41:57,986,986 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:41:57,986,986 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:41:57,986,986 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4104105000005802
[ 2024-01-04 16:41:57,988,988 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:45:13,632,632 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:45:13,997,997 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 16:45:13,998,998 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:45:13,998,998 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:45:13,998,998 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:45:13,999,999 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3641219999990426
[ 2024-01-04 16:45:13,999,999 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:45:14,002,002 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:45:14,347,347 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 16:45:14,348,348 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:45:14,349,349 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:45:14,349,349 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:45:14,350,350 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34616039999673376
[ 2024-01-04 16:45:14,351,351 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:45:14,359,359 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:45:15,089,089 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 16:45:15,090,090 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:45:15,090,090 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:45:15,090,090 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:45:15,091,091 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:45:15,091,091 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '3081', 'verifyId': 'b5bdc88538174a84a1e96c53e4290086'}
[ 2024-01-04 16:45:15,091,091 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:45:15,091,091 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:45:15,092,092 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3752745000019786
[ 2024-01-04 16:45:15,093,093 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:45:15,101,101 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:45:15,867,867 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 16:45:15,868,868 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:45:15,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:45:15,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:45:15,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:45:15,870,870 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '5715', 'verifyId': 'b82ee7ebb05b409a869f09d30a5162c7'}
[ 2024-01-04 16:45:15,870,870 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:45:15,870,870 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:45:15,870,870 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3756433999988076
[ 2024-01-04 16:45:15,873,873 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:45:15,878,878 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:45:16,680,680 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 123 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 16:45:16,680,680 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:45:16,680,680 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:45:16,680,680 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:45:16,681,681 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:45:16,681,681 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '1132', 'verifyId': 'f7cf3e560d39454d94eb7a3bcce25a28'}
[ 2024-01-04 16:45:16,681,681 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 16:45:16,681,681 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 16:45:16,681,681 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.450680599999032
[ 2024-01-04 16:45:16,682,682 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:57:22,580,580 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:57:23,331,331 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7796', 'verifyId': '385e8b9fbb1c4de48dc29e0662648a7b'}
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo KeyError('url') tblen=17>
[ 2024-01-04 16:57:23,332,332 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.35334250000232714
[ 2024-01-04 16:57:23,333,333 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:57:23,335,335 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:57:24,049,049 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:57:24,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:57:24,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:57:24,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:57:24,051,051 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '5465', 'verifyId': '8e93583f941643c5a1c477632b93228c'}
[ 2024-01-04 16:57:24,051,051 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:57:24,051,051 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo KeyError('url') tblen=17>
[ 2024-01-04 16:57:24,051,051 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3691491000026872
[ 2024-01-04 16:57:24,053,053 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:57:24,059,059 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:57:24,841,841 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:57:24,842,842 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:57:24,842,842 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:57:24,842,842 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:57:24,842,842 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5678', 'verifyId': '567be77ffc34436090b19361f2904aef'}
[ 2024-01-04 16:57:24,843,843 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:57:24,843,843 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo KeyError('url') tblen=17>
[ 2024-01-04 16:57:24,843,843 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4310270000023593
[ 2024-01-04 16:57:24,845,845 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:59:48,494,494 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:59:49,150,150 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 16:59:49,150,150 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:59:49,150,150 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 16:59:49,150,150 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4412884999983362
[ 2024-01-04 16:59:49,151,151 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:59:49,154,154 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:59:49,583,583 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 16:59:49,584,584 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:59:49,584,584 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 16:59:49,584,584 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34631669999726
[ 2024-01-04 16:59:49,585,585 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:59:49,589,589 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:59:50,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 16:59:50,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 16:59:50,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:59:50,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:59:50,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '2004', 'verifyId': '23adbf3d319349b4adf99f97ff03cb7c'}
[ 2024-01-04 16:59:50,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:59:50,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 16:59:50,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3682168000013917
[ 2024-01-04 16:59:50,386,386 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:59:50,389,389 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:59:51,152,152 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '3298', 'verifyId': '9b2bb6e35c2040f69b1cf2439aab54a2'}
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 16:59:51,153,153 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33841970000139554
[ 2024-01-04 16:59:51,154,154 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 16:59:51,157,157 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 16:59:51,977,977 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '1788', 'verifyId': '1e69775c8b664b989b918b6533f69396'}
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 16:59:51,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37798409999959404
[ 2024-01-04 16:59:51,979,979 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:00:39,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:00:40,354,354 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:00:40,355,355 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:00:40,355,355 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:00:40,355,355 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.346752599998581
[ 2024-01-04 17:00:40,356,356 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:00:40,359,359 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:00:40,779,779 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:00:40,779,779 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:00:40,779,779 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:00:40,779,779 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3350108000013279
[ 2024-01-04 17:00:40,780,780 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:00:40,783,783 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7309', 'verifyId': '7f8d58b75c37407fb6ac7dfb2b25b47f'}
[ 2024-01-04 17:00:41,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:00:41,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:00:41,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.340479200000118
[ 2024-01-04 17:00:41,530,530 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:00:41,532,532 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:00:42,342,342 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:00:42,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:00:42,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:00:42,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:00:42,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '1136', 'verifyId': 'ae93adcc6e254433974ed4921213f307'}
[ 2024-01-04 17:00:42,343,343 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:00:42,344,344 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:00:42,344,344 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.40585769999961485
[ 2024-01-04 17:00:42,345,345 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:00:42,347,347 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:00:43,168,168 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:00:43,168,168 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:00:43,168,168 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:00:43,169,169 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:00:43,169,169 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '1473', 'verifyId': 'ef69f59d108842d59d4d7a1d4e060b41'}
[ 2024-01-04 17:00:43,169,169 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:00:43,169,169 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:00:43,170,170 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37603930000113905
[ 2024-01-04 17:00:43,172,172 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:01:12,250,250 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:01:12,784,784 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:01:12,784,784 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:01:12,784,784 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:01:12,784,784 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3543533000010939
[ 2024-01-04 17:01:12,786,786 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:01:12,789,789 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:01:13,213,213 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:01:13,213,213 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:01:13,214,214 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:01:13,214,214 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33616650000112713
[ 2024-01-04 17:01:13,215,215 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:01:13,219,219 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5349', 'verifyId': '0ef5c84f2a24407ca3707cd1964e3abe'}
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:01:14,031,031 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4086109999989276
[ 2024-01-04 17:01:14,032,032 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:01:14,035,035 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '6850', 'verifyId': '46440dfcde3f42d2b0419968e1c8e2a1'}
[ 2024-01-04 17:01:14,838,838 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:01:14,839,839 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:01:14,839,839 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3460947000021406
[ 2024-01-04 17:01:14,840,840 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:01:14,842,842 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '6586', 'verifyId': '4412f2f317be439eb61565295d6cdcaf'}
[ 2024-01-04 17:01:15,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : failed
[ 2024-01-04 17:01:15,644,644 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : <ExceptionInfo TypeError('unsupported callable') tblen=19>
[ 2024-01-04 17:01:15,644,644 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3645897000023979
[ 2024-01-04 17:01:15,645,645 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:02:38,968,968 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:02:39,373,373 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:02:39,375,375 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:02:39,375,375 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:02:39,375,375 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:02:39,375,375 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4044112999981735
[ 2024-01-04 17:02:39,377,377 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:02:39,382,382 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:02:39,942,942 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:02:39,943,943 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:02:39,943,943 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:02:39,943,943 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:02:39,944,944 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.5581005000021833
[ 2024-01-04 17:02:39,945,945 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:02:39,952,952 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:02:40,797,797 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '3764', 'verifyId': 'bbc847577b48415487a6470777e566ae'}
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:02:40,798,798 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37565729999914765
[ 2024-01-04 17:02:40,800,800 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:02:40,803,803 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:02:41,562,562 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '9489', 'verifyId': '4d80d67927fc413c97c0f01383651826'}
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:02:41,563,563 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.38302869999824907
[ 2024-01-04 17:02:41,565,565 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:02:41,567,567 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:02:42,314,314 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:02:42,314,314 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:02:42,314,314 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7474', 'verifyId': 'fd33da73f0b74617b0f901c6437d7f2c'}
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:02:42,316,316 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.39553689999956987
[ 2024-01-04 17:02:42,317,317 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:07:37,370,370 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:07:37,743,743 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:07:37,744,744 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:07:37,744,744 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:07:37,745,745 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:07:37,745,745 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3728709999995772
[ 2024-01-04 17:07:37,746,746 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:07:37,748,748 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:07:38,089,089 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:07:38,089,089 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:07:38,089,089 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:07:38,089,089 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:07:38,090,090 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33964709999781917
[ 2024-01-04 17:07:38,091,091 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:07:38,094,094 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:07:38,864,864 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '8386', 'verifyId': 'aa790be970684fe18bdea5f6fed4a843'}
[ 2024-01-04 17:07:38,865,865 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:07:38,866,866 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:07:38,866,866 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.42152400000122725
[ 2024-01-04 17:07:38,867,867 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:07:38,869,869 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:07:39,689,689 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:07:39,689,689 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '8948', 'verifyId': '515bf2ea76ab40e48431dbeb5de75040'}
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:07:39,690,690 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.38348319999931846
[ 2024-01-04 17:07:39,691,691 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:07:39,695,695 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:07:40,495,495 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '8012', 'verifyId': '7035ae27eb37410389ba9e1303f110eb'}
[ 2024-01-04 17:07:40,496,496 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:07:40,497,497 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:07:40,497,497 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.4140445999983058
[ 2024-01-04 17:07:40,498,498 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:11:35,249,249 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:11:35,624,624 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:11:35,624,624 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:11:35,624,624 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:11:35,624,624 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:11:35,624,624 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37268050000056974
[ 2024-01-04 17:11:35,625,625 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:11:35,628,628 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:11:35,973,973 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:11:35,973,973 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:11:35,973,973 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:11:35,974,974 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:11:35,974,974 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3447194000000309
[ 2024-01-04 17:11:35,975,975 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:11:35,978,978 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:11:36,670,670 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:11:36,670,670 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:11:36,670,670 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:11:36,670,670 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:11:36,671,671 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:11:36,671,671 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5840', 'verifyId': 'fd41e912ed9b48a0aa6744d7f8503c93'}
[ 2024-01-04 17:11:36,671,671 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:11:36,671,671 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:11:36,671,671 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36023869999917224
[ 2024-01-04 17:11:36,673,673 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:11:36,675,675 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:11:37,359,359 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:11:37,359,359 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:11:37,359,359 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:11:37,359,359 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:11:37,360,360 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:11:37,360,360 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '7066', 'verifyId': '042ee897926940c49ac3cf00fd2584d7'}
[ 2024-01-04 17:11:37,360,360 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:11:37,360,360 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:11:37,360,360 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34752239999943413
[ 2024-01-04 17:11:37,361,361 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:11:37,363,363 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:11:38,050,050 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:11:38,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:11:38,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:11:38,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:11:38,050,050 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:11:38,052,052 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '6529', 'verifyId': '7e5c673fa3e849b4ae32b80dcaa7d669'}
[ 2024-01-04 17:11:38,052,052 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:11:38,052,052 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:11:38,052,052 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36071150000134367
[ 2024-01-04 17:11:38,052,052 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:30:45,791,791 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:30:46,163,163 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:30:46,164,164 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:30:46,164,164 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:30:46,165,165 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:30:46,165,165 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37198889999854146
[ 2024-01-04 17:30:46,167,167 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:30:46,172,172 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:30:46,523,523 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:30:46,524,524 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:30:46,524,524 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:30:46,524,524 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:30:46,524,524 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3500906000008399
[ 2024-01-04 17:30:46,525,525 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:30:46,528,528 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:30:47,250,250 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:30:47,250,250 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:30:47,250,250 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:30:47,250,250 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:30:47,251,251 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:30:47,251,251 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '3334', 'verifyId': 'ad8661693fee42c09b82610e36605e6c'}
[ 2024-01-04 17:30:47,251,251 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:30:47,251,251 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:30:47,251,251 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3452746000002662
[ 2024-01-04 17:30:47,252,252 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:30:47,254,254 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:30:47,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '8112', 'verifyId': 'e8b1485de3df4ca5b7b974491bb59ed7'}
[ 2024-01-04 17:30:47,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:30:47,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:30:47,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33572819999972126
[ 2024-01-04 17:30:47,940,940 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:30:47,942,942 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:30:48,628,628 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7515', 'verifyId': '269f1fd0e43c48fbad3c77ed43c948d6'}
[ 2024-01-04 17:30:48,629,629 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:30:48,630,630 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:30:48,630,630 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36112369999682414
[ 2024-01-04 17:30:48,630,630 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:34:05,785,785 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:34:06,127,127 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:34:06,134,134 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:34:06,134,134 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:34:06,134,134 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:34:06,134,134 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34726539999974193
[ 2024-01-04 17:34:06,135,135 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:34:06,137,137 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:34:06,521,521 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:34:06,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:34:06,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:34:06,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:34:06,529,529 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3908472000002803
[ 2024-01-04 17:34:06,530,530 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:34:06,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:34:07,252,252 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:34:07,252,252 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:34:07,252,252 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:34:07,252,252 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:34:07,252,252 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:34:07,253,253 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '9627', 'verifyId': 'b33ef099bd4049e1a971f7a71b3c9711'}
[ 2024-01-04 17:34:07,254,254 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:34:07,254,254 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:34:07,254,254 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3864773999994213
[ 2024-01-04 17:34:07,255,255 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:34:07,257,257 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:34:07,917,917 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '3936', 'verifyId': '19e8352db30543b4b6139900f21f2ba2'}
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:34:07,918,918 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33510999999998603
[ 2024-01-04 17:34:07,919,919 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:34:07,922,922 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:34:08,642,642 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:34:08,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:34:08,644,644 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:34:08,644,644 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:34:08,644,644 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:34:08,645,645 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '9727', 'verifyId': '2fd0ec68c8b842f8b726b87e9221029c'}
[ 2024-01-04 17:34:08,645,645 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:34:08,645,645 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:34:08,646,646 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3886433000006946
[ 2024-01-04 17:34:08,648,648 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:35:19,494,494 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:35:19,865,865 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:35:19,875,875 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:35:19,875,875 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:35:19,876,876 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:35:19,876,876 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37943430000086664
[ 2024-01-04 17:35:19,878,878 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:35:19,886,886 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:35:20,259,259 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:35:20,267,267 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:35:20,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:35:20,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:35:20,268,268 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.37902829999802634
[ 2024-01-04 17:35:20,271,271 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:35:20,275,275 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:35:20,938,938 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5332', 'verifyId': 'de9cdc6829dc46e4951eaf9cac4dc845'}
[ 2024-01-04 17:35:20,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:35:20,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:35:20,939,939 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3296733999995922
[ 2024-01-04 17:35:20,940,940 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:35:20,942,942 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:35:21,635,635 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:35:21,635,635 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:35:21,636,636 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:35:21,636,636 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:35:21,636,636 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:35:21,636,636 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '7790', 'verifyId': '6de38f7d81424f0fa89b2d336a4cf76b'}
[ 2024-01-04 17:35:21,637,637 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:35:21,637,637 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:35:21,637,637 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3491301999965799
[ 2024-01-04 17:35:21,640,640 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:35:21,643,643 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:35:22,382,382 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:35:22,383,383 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:35:22,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:35:22,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:35:22,384,384 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:35:22,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '8380', 'verifyId': '477edb7efb2c419fb9b87baf9882b5a3'}
[ 2024-01-04 17:35:22,385,385 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:35:22,386,386 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:35:22,386,386 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3976330000004964
[ 2024-01-04 17:35:22,389,389 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:38:15,095,095 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:38:15,501,501 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:38:15,511,511 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:38:15,511,511 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:38:15,512,512 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:38:15,512,512 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.41361220000180765
[ 2024-01-04 17:38:15,514,514 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:38:15,519,519 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:38:15,911,911 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:38:15,926,926 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:38:15,927,927 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:38:15,927,927 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:38:15,928,928 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.404944499998237
[ 2024-01-04 17:38:15,931,931 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:38:15,945,945 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:38:16,629,629 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:38:16,630,630 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:38:16,631,631 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:38:16,631,631 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:38:16,631,631 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:38:16,632,632 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '5927', 'verifyId': '3bbc66230de043508a9f035d6df38d13'}
[ 2024-01-04 17:38:16,632,632 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:38:16,632,632 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:38:16,632,632 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.33690909999859286
[ 2024-01-04 17:38:16,634,634 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:38:16,639,639 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:38:17,340,340 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:38:17,340,340 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:38:17,340,340 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:38:17,340,340 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:38:17,340,340 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:38:17,341,341 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '2734', 'verifyId': '03ca0bbf7f7f464dbdc45b855deb3eec'}
[ 2024-01-04 17:38:17,341,341 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:38:17,341,341 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:38:17,341,341 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3642963000020245
[ 2024-01-04 17:38:17,342,342 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:38:17,344,344 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:38:18,063,063 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:38:18,063,063 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : test_cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:38:18,064,064 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:38:18,064,064 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:38:18,064,064 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:38:18,065,065 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '7121', 'verifyId': '15720b50ce9a42a7a9c67e5515f351b3'}
[ 2024-01-04 17:38:18,065,065 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:38:18,065,065 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:38:18,066,066 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3715082999988226
[ 2024-01-04 17:38:18,068,068 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:45:03,399,399 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:45:03,740,740 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 10 == 10
[ 2024-01-04 17:45:03,747,747 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page0]
[ 2024-01-04 17:45:03,747,747 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:45:03,747,747 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:45:03,747,747 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.34690969999792287
[ 2024-01-04 17:45:03,748,748 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:45:03,751,751 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:45:04,133,133 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 20 == 20
[ 2024-01-04 17:45:04,140,140 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : cases/test_crm/test_crm_page.py::TestCRM::test_crm_page[page1]
[ 2024-01-04 17:45:04,140,140 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:45:04,140,140 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:45:04,140,140 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3883490000007441
[ 2024-01-04 17:45:04,141,141 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:45:04,145,145 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:45:04,848,848 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 当前账号不存在 == 当前账号不存在
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : cases/test_login/test_login.py::TestLogin::test_login[login0]
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 3 >
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi288', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '8225', 'verifyId': '4190b3cd30f4470284ec74d76bb91f0d'}
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:45:04,849,849 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3419659999999567
[ 2024-01-04 17:45:04,850,850 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:45:04,852,852 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:45:05,533,533 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : 密码错误,输入密码不匹配 == 密码错误,输入密码不匹配
[ 2024-01-04 17:45:05,533,533 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : cases/test_login/test_login.py::TestLogin::test_login[login1]
[ 2024-01-04 17:45:05,533,533 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 4 >
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': '5690dddfa28ae085d23518a035707282', 'verifyCode': '5702', 'verifyId': '277beed259844ac68891971c910048bd'}
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:45:05,534,534 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.3427071000005526
[ 2024-01-04 17:45:05,535,535 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
[ 2024-01-04 17:45:05,537,537 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 39 / auto_log ] -- -> *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  *_*  
[ 2024-01-04 17:45:06,232,232 ]  [ INFO     ]  [ MainThread  ]  [ base_assert.py / 125 / assert_common ] -- -> 断言通过 : OK == OK
[ 2024-01-04 17:45:06,233,233 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 51 / pytest_runtest_makereport ] -- -> 用例位置 : cases/test_login/test_login.py::TestLogin::test_login[login2]
[ 2024-01-04 17:45:06,233,233 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 57 / pytest_runtest_makereport ] -- -> 数据位置 : Sheet: < 登录模块 > RowNumber: < 5 >
[ 2024-01-04 17:45:06,234,234 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 58 / pytest_runtest_makereport ] -- -> 请求地址 : /user/agency_user/username_pwd/sign_in
[ 2024-01-04 17:45:06,234,234 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 59 / pytest_runtest_makereport ] -- -> 请求方法 : post
[ 2024-01-04 17:45:06,234,234 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 60 / pytest_runtest_makereport ] -- -> 请求参数 : {'authType': 'usernamePassword', 'idType': 'USERNAME', 'loginId': 'ceshi2', 'password': 'dc483e80a7a0bd9ef71d8cf973673924', 'verifyCode': '2198', 'verifyId': '7734e28f5fa840d991f1ad19ed528780'}
[ 2024-01-04 17:45:06,235,235 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 61 / pytest_runtest_makereport ] -- -> 测试结果 : passed
[ 2024-01-04 17:45:06,235,235 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 62 / pytest_runtest_makereport ] -- -> 异常信息 : None
[ 2024-01-04 17:45:06,236,236 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 63 / pytest_runtest_makereport ] -- -> 用例耗时 : 0.36630349999904865
[ 2024-01-04 17:45:06,239,239 ]  [ INFO     ]  [ MainThread  ]  [ conftest.py / 41 / auto_log ] -- -> *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  *¯*  
